version: '3.4'

services:
  messageconsumer:
    build: ./Message.Consumer
    restart: always
    depends_on: 
      - "rabbitmq"
      - "mongo"

  mongo:
    image: mongo:4.0.19
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=mongo
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - "27017:27017"

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq:/etc/rabbitmq/
    ports:
    - "4369:4369"
    - "5672:5672"
    - "5671:5671"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"